; Auto-generated. Do not edit!


(cl:in-package yumi_robot_service-srv)


;//! \htmlinclude yumi_execute-request.msg.html

(cl:defclass <yumi_execute-request> (roslisp-msg-protocol:ros-message)
  ((command
    :reader command
    :initarg :command
    :type cl:string
    :initform "")
   (Qt
    :reader Qt
    :initarg :Qt
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (group_name
    :reader group_name
    :initarg :group_name
    :type cl:string
    :initform "")
   (t
    :reader t
    :initarg :t
    :type cl:integer
    :initform 0))
)

(cl:defclass yumi_execute-request (<yumi_execute-request>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <yumi_execute-request>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'yumi_execute-request)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name yumi_robot_service-srv:<yumi_execute-request> is deprecated: use yumi_robot_service-srv:yumi_execute-request instead.")))

(cl:ensure-generic-function 'command-val :lambda-list '(m))
(cl:defmethod command-val ((m <yumi_execute-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader yumi_robot_service-srv:command-val is deprecated.  Use yumi_robot_service-srv:command instead.")
  (command m))

(cl:ensure-generic-function 'Qt-val :lambda-list '(m))
(cl:defmethod Qt-val ((m <yumi_execute-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader yumi_robot_service-srv:Qt-val is deprecated.  Use yumi_robot_service-srv:Qt instead.")
  (Qt m))

(cl:ensure-generic-function 'group_name-val :lambda-list '(m))
(cl:defmethod group_name-val ((m <yumi_execute-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader yumi_robot_service-srv:group_name-val is deprecated.  Use yumi_robot_service-srv:group_name instead.")
  (group_name m))

(cl:ensure-generic-function 't-val :lambda-list '(m))
(cl:defmethod t-val ((m <yumi_execute-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader yumi_robot_service-srv:t-val is deprecated.  Use yumi_robot_service-srv:t instead.")
  (t m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <yumi_execute-request>) ostream)
  "Serializes a message object of type '<yumi_execute-request>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'command))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'command))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Qt))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Qt))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'group_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'group_name))
  (cl:let* ((signed (cl:slot-value msg 't)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <yumi_execute-request>) istream)
  "Deserializes a message object of type '<yumi_execute-request>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'command) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'command) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Qt) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Qt)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'group_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'group_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 't) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<yumi_execute-request>)))
  "Returns string type for a service object of type '<yumi_execute-request>"
  "yumi_robot_service/yumi_executeRequest")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'yumi_execute-request)))
  "Returns string type for a service object of type 'yumi_execute-request"
  "yumi_robot_service/yumi_executeRequest")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<yumi_execute-request>)))
  "Returns md5sum for a message object of type '<yumi_execute-request>"
  "24a5a4d139f797e276899139cf7239b0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'yumi_execute-request)))
  "Returns md5sum for a message object of type 'yumi_execute-request"
  "24a5a4d139f797e276899139cf7239b0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<yumi_execute-request>)))
  "Returns full string definition for message of type '<yumi_execute-request>"
  (cl:format cl:nil "string command~%float64[] Qt~%string group_name~%int64 t~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'yumi_execute-request)))
  "Returns full string definition for message of type 'yumi_execute-request"
  (cl:format cl:nil "string command~%float64[] Qt~%string group_name~%int64 t~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <yumi_execute-request>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'command))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Qt) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:length (cl:slot-value msg 'group_name))
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <yumi_execute-request>))
  "Converts a ROS message object to a list"
  (cl:list 'yumi_execute-request
    (cl:cons ':command (command msg))
    (cl:cons ':Qt (Qt msg))
    (cl:cons ':group_name (group_name msg))
    (cl:cons ':t (t msg))
))
;//! \htmlinclude yumi_execute-response.msg.html

(cl:defclass <yumi_execute-response> (roslisp-msg-protocol:ros-message)
  ((xt_hat
    :reader xt_hat
    :initarg :xt_hat
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (Qt_hat
    :reader Qt_hat
    :initarg :Qt_hat
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (x_next
    :reader x_next
    :initarg :x_next
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (Q_next
    :reader Q_next
    :initarg :Q_next
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (if_collide
    :reader if_collide
    :initarg :if_collide
    :type cl:float
    :initform 0.0))
)

(cl:defclass yumi_execute-response (<yumi_execute-response>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <yumi_execute-response>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'yumi_execute-response)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name yumi_robot_service-srv:<yumi_execute-response> is deprecated: use yumi_robot_service-srv:yumi_execute-response instead.")))

(cl:ensure-generic-function 'xt_hat-val :lambda-list '(m))
(cl:defmethod xt_hat-val ((m <yumi_execute-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader yumi_robot_service-srv:xt_hat-val is deprecated.  Use yumi_robot_service-srv:xt_hat instead.")
  (xt_hat m))

(cl:ensure-generic-function 'Qt_hat-val :lambda-list '(m))
(cl:defmethod Qt_hat-val ((m <yumi_execute-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader yumi_robot_service-srv:Qt_hat-val is deprecated.  Use yumi_robot_service-srv:Qt_hat instead.")
  (Qt_hat m))

(cl:ensure-generic-function 'x_next-val :lambda-list '(m))
(cl:defmethod x_next-val ((m <yumi_execute-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader yumi_robot_service-srv:x_next-val is deprecated.  Use yumi_robot_service-srv:x_next instead.")
  (x_next m))

(cl:ensure-generic-function 'Q_next-val :lambda-list '(m))
(cl:defmethod Q_next-val ((m <yumi_execute-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader yumi_robot_service-srv:Q_next-val is deprecated.  Use yumi_robot_service-srv:Q_next instead.")
  (Q_next m))

(cl:ensure-generic-function 'if_collide-val :lambda-list '(m))
(cl:defmethod if_collide-val ((m <yumi_execute-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader yumi_robot_service-srv:if_collide-val is deprecated.  Use yumi_robot_service-srv:if_collide instead.")
  (if_collide m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <yumi_execute-response>) ostream)
  "Serializes a message object of type '<yumi_execute-response>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'xt_hat))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'xt_hat))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Qt_hat))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Qt_hat))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'x_next))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'x_next))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Q_next))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Q_next))
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'if_collide))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <yumi_execute-response>) istream)
  "Deserializes a message object of type '<yumi_execute-response>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'xt_hat) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'xt_hat)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Qt_hat) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Qt_hat)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'x_next) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'x_next)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Q_next) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Q_next)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'if_collide) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<yumi_execute-response>)))
  "Returns string type for a service object of type '<yumi_execute-response>"
  "yumi_robot_service/yumi_executeResponse")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'yumi_execute-response)))
  "Returns string type for a service object of type 'yumi_execute-response"
  "yumi_robot_service/yumi_executeResponse")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<yumi_execute-response>)))
  "Returns md5sum for a message object of type '<yumi_execute-response>"
  "24a5a4d139f797e276899139cf7239b0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'yumi_execute-response)))
  "Returns md5sum for a message object of type 'yumi_execute-response"
  "24a5a4d139f797e276899139cf7239b0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<yumi_execute-response>)))
  "Returns full string definition for message of type '<yumi_execute-response>"
  (cl:format cl:nil "float64[] xt_hat~%float64[] Qt_hat~%float64[] x_next~%float64[] Q_next~%float64 if_collide~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'yumi_execute-response)))
  "Returns full string definition for message of type 'yumi_execute-response"
  (cl:format cl:nil "float64[] xt_hat~%float64[] Qt_hat~%float64[] x_next~%float64[] Q_next~%float64 if_collide~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <yumi_execute-response>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'xt_hat) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Qt_hat) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'x_next) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Q_next) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <yumi_execute-response>))
  "Converts a ROS message object to a list"
  (cl:list 'yumi_execute-response
    (cl:cons ':xt_hat (xt_hat msg))
    (cl:cons ':Qt_hat (Qt_hat msg))
    (cl:cons ':x_next (x_next msg))
    (cl:cons ':Q_next (Q_next msg))
    (cl:cons ':if_collide (if_collide msg))
))
(cl:defmethod roslisp-msg-protocol:service-request-type ((msg (cl:eql 'yumi_execute)))
  'yumi_execute-request)
(cl:defmethod roslisp-msg-protocol:service-response-type ((msg (cl:eql 'yumi_execute)))
  'yumi_execute-response)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'yumi_execute)))
  "Returns string type for a service object of type '<yumi_execute>"
  "yumi_robot_service/yumi_execute")