// Generated by gencpp from file inspire_hand/get_angle_act.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_GET_ANGLE_ACT_H
#define INSPIRE_HAND_MESSAGE_GET_ANGLE_ACT_H

#include <ros/service_traits.h>


#include <inspire_hand/get_angle_actRequest.h>
#include <inspire_hand/get_angle_actResponse.h>


namespace inspire_hand
{

struct get_angle_act
{

typedef get_angle_actRequest Request;
typedef get_angle_actResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_angle_act
} // namespace inspire_hand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::inspire_hand::get_angle_act > {
  static const char* value()
  {
    return "2329a3c808aea9d534c8a2279948da90";
  }

  static const char* value(const ::inspire_hand::get_angle_act&) { return value(); }
};

template<>
struct DataType< ::inspire_hand::get_angle_act > {
  static const char* value()
  {
    return "inspire_hand/get_angle_act";
  }

  static const char* value(const ::inspire_hand::get_angle_act&) { return value(); }
};


// service_traits::MD5Sum< ::inspire_hand::get_angle_actRequest> should match 
// service_traits::MD5Sum< ::inspire_hand::get_angle_act > 
template<>
struct MD5Sum< ::inspire_hand::get_angle_actRequest>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::get_angle_act >::value();
  }
  static const char* value(const ::inspire_hand::get_angle_actRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::get_angle_actRequest> should match 
// service_traits::DataType< ::inspire_hand::get_angle_act > 
template<>
struct DataType< ::inspire_hand::get_angle_actRequest>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::get_angle_act >::value();
  }
  static const char* value(const ::inspire_hand::get_angle_actRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::inspire_hand::get_angle_actResponse> should match 
// service_traits::MD5Sum< ::inspire_hand::get_angle_act > 
template<>
struct MD5Sum< ::inspire_hand::get_angle_actResponse>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::get_angle_act >::value();
  }
  static const char* value(const ::inspire_hand::get_angle_actResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::get_angle_actResponse> should match 
// service_traits::DataType< ::inspire_hand::get_angle_act > 
template<>
struct DataType< ::inspire_hand::get_angle_actResponse>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::get_angle_act >::value();
  }
  static const char* value(const ::inspire_hand::get_angle_actResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_GET_ANGLE_ACT_H
