// Generated by gencpp from file inspire_hand/get_angle_setResponse.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_GET_ANGLE_SETRESPONSE_H
#define INSPIRE_HAND_MESSAGE_GET_ANGLE_SETRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inspire_hand
{
template <class ContainerAllocator>
struct get_angle_setResponse_
{
  typedef get_angle_setResponse_<ContainerAllocator> Type;

  get_angle_setResponse_()
    : setangle()  {
      setangle.assign(0.0);
  }
  get_angle_setResponse_(const ContainerAllocator& _alloc)
    : setangle()  {
  (void)_alloc;
      setangle.assign(0.0);
  }



   typedef boost::array<float, 6>  _setangle_type;
  _setangle_type setangle;





  typedef boost::shared_ptr< ::inspire_hand::get_angle_setResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inspire_hand::get_angle_setResponse_<ContainerAllocator> const> ConstPtr;

}; // struct get_angle_setResponse_

typedef ::inspire_hand::get_angle_setResponse_<std::allocator<void> > get_angle_setResponse;

typedef boost::shared_ptr< ::inspire_hand::get_angle_setResponse > get_angle_setResponsePtr;
typedef boost::shared_ptr< ::inspire_hand::get_angle_setResponse const> get_angle_setResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inspire_hand::get_angle_setResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inspire_hand::get_angle_setResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inspire_hand

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::get_angle_setResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::get_angle_setResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::get_angle_setResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::get_angle_setResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::get_angle_setResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::get_angle_setResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inspire_hand::get_angle_setResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9345778c384982b35dad72748c701694";
  }

  static const char* value(const ::inspire_hand::get_angle_setResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9345778c384982b3ULL;
  static const uint64_t static_value2 = 0x5dad72748c701694ULL;
};

template<class ContainerAllocator>
struct DataType< ::inspire_hand::get_angle_setResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inspire_hand/get_angle_setResponse";
  }

  static const char* value(const ::inspire_hand::get_angle_setResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inspire_hand::get_angle_setResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[6] setangle\n\
";
  }

  static const char* value(const ::inspire_hand::get_angle_setResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inspire_hand::get_angle_setResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.setangle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_angle_setResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inspire_hand::get_angle_setResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inspire_hand::get_angle_setResponse_<ContainerAllocator>& v)
  {
    s << indent << "setangle[]" << std::endl;
    for (size_t i = 0; i < v.setangle.size(); ++i)
    {
      s << indent << "  setangle[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.setangle[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_GET_ANGLE_SETRESPONSE_H
