// Generated by gencpp from file inspire_hand/get_pos_set.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_GET_POS_SET_H
#define INSPIRE_HAND_MESSAGE_GET_POS_SET_H

#include <ros/service_traits.h>


#include <inspire_hand/get_pos_setRequest.h>
#include <inspire_hand/get_pos_setResponse.h>


namespace inspire_hand
{

struct get_pos_set
{

typedef get_pos_setRequest Request;
typedef get_pos_setResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_pos_set
} // namespace inspire_hand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::inspire_hand::get_pos_set > {
  static const char* value()
  {
    return "cffb9069f96661e23c6011a89561b5a1";
  }

  static const char* value(const ::inspire_hand::get_pos_set&) { return value(); }
};

template<>
struct DataType< ::inspire_hand::get_pos_set > {
  static const char* value()
  {
    return "inspire_hand/get_pos_set";
  }

  static const char* value(const ::inspire_hand::get_pos_set&) { return value(); }
};


// service_traits::MD5Sum< ::inspire_hand::get_pos_setRequest> should match 
// service_traits::MD5Sum< ::inspire_hand::get_pos_set > 
template<>
struct MD5Sum< ::inspire_hand::get_pos_setRequest>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::get_pos_set >::value();
  }
  static const char* value(const ::inspire_hand::get_pos_setRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::get_pos_setRequest> should match 
// service_traits::DataType< ::inspire_hand::get_pos_set > 
template<>
struct DataType< ::inspire_hand::get_pos_setRequest>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::get_pos_set >::value();
  }
  static const char* value(const ::inspire_hand::get_pos_setRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::inspire_hand::get_pos_setResponse> should match 
// service_traits::MD5Sum< ::inspire_hand::get_pos_set > 
template<>
struct MD5Sum< ::inspire_hand::get_pos_setResponse>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::get_pos_set >::value();
  }
  static const char* value(const ::inspire_hand::get_pos_setResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::get_pos_setResponse> should match 
// service_traits::DataType< ::inspire_hand::get_pos_set > 
template<>
struct DataType< ::inspire_hand::get_pos_setResponse>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::get_pos_set >::value();
  }
  static const char* value(const ::inspire_hand::get_pos_setResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_GET_POS_SET_H
