// Generated by gencpp from file inspire_hand/get_angle_set.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_GET_ANGLE_SET_H
#define INSPIRE_HAND_MESSAGE_GET_ANGLE_SET_H

#include <ros/service_traits.h>


#include <inspire_hand/get_angle_setRequest.h>
#include <inspire_hand/get_angle_setResponse.h>


namespace inspire_hand
{

struct get_angle_set
{

typedef get_angle_setRequest Request;
typedef get_angle_setResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_angle_set
} // namespace inspire_hand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::inspire_hand::get_angle_set > {
  static const char* value()
  {
    return "9345778c384982b35dad72748c701694";
  }

  static const char* value(const ::inspire_hand::get_angle_set&) { return value(); }
};

template<>
struct DataType< ::inspire_hand::get_angle_set > {
  static const char* value()
  {
    return "inspire_hand/get_angle_set";
  }

  static const char* value(const ::inspire_hand::get_angle_set&) { return value(); }
};


// service_traits::MD5Sum< ::inspire_hand::get_angle_setRequest> should match 
// service_traits::MD5Sum< ::inspire_hand::get_angle_set > 
template<>
struct MD5Sum< ::inspire_hand::get_angle_setRequest>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::get_angle_set >::value();
  }
  static const char* value(const ::inspire_hand::get_angle_setRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::get_angle_setRequest> should match 
// service_traits::DataType< ::inspire_hand::get_angle_set > 
template<>
struct DataType< ::inspire_hand::get_angle_setRequest>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::get_angle_set >::value();
  }
  static const char* value(const ::inspire_hand::get_angle_setRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::inspire_hand::get_angle_setResponse> should match 
// service_traits::MD5Sum< ::inspire_hand::get_angle_set > 
template<>
struct MD5Sum< ::inspire_hand::get_angle_setResponse>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::get_angle_set >::value();
  }
  static const char* value(const ::inspire_hand::get_angle_setResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::get_angle_setResponse> should match 
// service_traits::DataType< ::inspire_hand::get_angle_set > 
template<>
struct DataType< ::inspire_hand::get_angle_setResponse>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::get_angle_set >::value();
  }
  static const char* value(const ::inspire_hand::get_angle_setResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_GET_ANGLE_SET_H
