// Generated by gencpp from file inspire_hand/get_current.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_GET_CURRENT_H
#define INSPIRE_HAND_MESSAGE_GET_CURRENT_H

#include <ros/service_traits.h>


#include <inspire_hand/get_currentRequest.h>
#include <inspire_hand/get_currentResponse.h>


namespace inspire_hand
{

struct get_current
{

typedef get_currentRequest Request;
typedef get_currentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_current
} // namespace inspire_hand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::inspire_hand::get_current > {
  static const char* value()
  {
    return "11d573dfe70ac25437cf58ad00cf741d";
  }

  static const char* value(const ::inspire_hand::get_current&) { return value(); }
};

template<>
struct DataType< ::inspire_hand::get_current > {
  static const char* value()
  {
    return "inspire_hand/get_current";
  }

  static const char* value(const ::inspire_hand::get_current&) { return value(); }
};


// service_traits::MD5Sum< ::inspire_hand::get_currentRequest> should match 
// service_traits::MD5Sum< ::inspire_hand::get_current > 
template<>
struct MD5Sum< ::inspire_hand::get_currentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::get_current >::value();
  }
  static const char* value(const ::inspire_hand::get_currentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::get_currentRequest> should match 
// service_traits::DataType< ::inspire_hand::get_current > 
template<>
struct DataType< ::inspire_hand::get_currentRequest>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::get_current >::value();
  }
  static const char* value(const ::inspire_hand::get_currentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::inspire_hand::get_currentResponse> should match 
// service_traits::MD5Sum< ::inspire_hand::get_current > 
template<>
struct MD5Sum< ::inspire_hand::get_currentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::get_current >::value();
  }
  static const char* value(const ::inspire_hand::get_currentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::get_currentResponse> should match 
// service_traits::DataType< ::inspire_hand::get_current > 
template<>
struct DataType< ::inspire_hand::get_currentResponse>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::get_current >::value();
  }
  static const char* value(const ::inspire_hand::get_currentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_GET_CURRENT_H
