// Generated by gencpp from file inspire_hand/set_redu_ratioRequest.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_SET_REDU_RATIOREQUEST_H
#define INSPIRE_HAND_MESSAGE_SET_REDU_RATIOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inspire_hand
{
template <class ContainerAllocator>
struct set_redu_ratioRequest_
{
  typedef set_redu_ratioRequest_<ContainerAllocator> Type;

  set_redu_ratioRequest_()
    : redu_ratio(0)  {
    }
  set_redu_ratioRequest_(const ContainerAllocator& _alloc)
    : redu_ratio(0)  {
  (void)_alloc;
    }



   typedef int32_t _redu_ratio_type;
  _redu_ratio_type redu_ratio;





  typedef boost::shared_ptr< ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_redu_ratioRequest_

typedef ::inspire_hand::set_redu_ratioRequest_<std::allocator<void> > set_redu_ratioRequest;

typedef boost::shared_ptr< ::inspire_hand::set_redu_ratioRequest > set_redu_ratioRequestPtr;
typedef boost::shared_ptr< ::inspire_hand::set_redu_ratioRequest const> set_redu_ratioRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inspire_hand

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f53cf3e807cecd6ac535ce2490110114";
  }

  static const char* value(const ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf53cf3e807cecd6aULL;
  static const uint64_t static_value2 = 0xc535ce2490110114ULL;
};

template<class ContainerAllocator>
struct DataType< ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inspire_hand/set_redu_ratioRequest";
  }

  static const char* value(const ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 redu_ratio\n\
";
  }

  static const char* value(const ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.redu_ratio);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_redu_ratioRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inspire_hand::set_redu_ratioRequest_<ContainerAllocator>& v)
  {
    s << indent << "redu_ratio: ";
    Printer<int32_t>::stream(s, indent + "  ", v.redu_ratio);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_SET_REDU_RATIOREQUEST_H
