// Generated by gencpp from file inspire_hand/set_redu_ratioResponse.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_SET_REDU_RATIORESPONSE_H
#define INSPIRE_HAND_MESSAGE_SET_REDU_RATIORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inspire_hand
{
template <class ContainerAllocator>
struct set_redu_ratioResponse_
{
  typedef set_redu_ratioResponse_<ContainerAllocator> Type;

  set_redu_ratioResponse_()
    : redu_ratiograb(false)  {
    }
  set_redu_ratioResponse_(const ContainerAllocator& _alloc)
    : redu_ratiograb(false)  {
  (void)_alloc;
    }



   typedef uint8_t _redu_ratiograb_type;
  _redu_ratiograb_type redu_ratiograb;





  typedef boost::shared_ptr< ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_redu_ratioResponse_

typedef ::inspire_hand::set_redu_ratioResponse_<std::allocator<void> > set_redu_ratioResponse;

typedef boost::shared_ptr< ::inspire_hand::set_redu_ratioResponse > set_redu_ratioResponsePtr;
typedef boost::shared_ptr< ::inspire_hand::set_redu_ratioResponse const> set_redu_ratioResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inspire_hand

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d1b975ad952b9874bc1e1818834aa76";
  }

  static const char* value(const ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d1b975ad952b987ULL;
  static const uint64_t static_value2 = 0x4bc1e1818834aa76ULL;
};

template<class ContainerAllocator>
struct DataType< ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inspire_hand/set_redu_ratioResponse";
  }

  static const char* value(const ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool redu_ratiograb\n\
\n\
";
  }

  static const char* value(const ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.redu_ratiograb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_redu_ratioResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inspire_hand::set_redu_ratioResponse_<ContainerAllocator>& v)
  {
    s << indent << "redu_ratiograb: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.redu_ratiograb);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_SET_REDU_RATIORESPONSE_H
