// Generated by gencpp from file inspire_hand/set_reset_para.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_SET_RESET_PARA_H
#define INSPIRE_HAND_MESSAGE_SET_RESET_PARA_H

#include <ros/service_traits.h>


#include <inspire_hand/set_reset_paraRequest.h>
#include <inspire_hand/set_reset_paraResponse.h>


namespace inspire_hand
{

struct set_reset_para
{

typedef set_reset_paraRequest Request;
typedef set_reset_paraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_reset_para
} // namespace inspire_hand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::inspire_hand::set_reset_para > {
  static const char* value()
  {
    return "09c8a3c1c50f7ff06e4871280095d7ee";
  }

  static const char* value(const ::inspire_hand::set_reset_para&) { return value(); }
};

template<>
struct DataType< ::inspire_hand::set_reset_para > {
  static const char* value()
  {
    return "inspire_hand/set_reset_para";
  }

  static const char* value(const ::inspire_hand::set_reset_para&) { return value(); }
};


// service_traits::MD5Sum< ::inspire_hand::set_reset_paraRequest> should match 
// service_traits::MD5Sum< ::inspire_hand::set_reset_para > 
template<>
struct MD5Sum< ::inspire_hand::set_reset_paraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::set_reset_para >::value();
  }
  static const char* value(const ::inspire_hand::set_reset_paraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::set_reset_paraRequest> should match 
// service_traits::DataType< ::inspire_hand::set_reset_para > 
template<>
struct DataType< ::inspire_hand::set_reset_paraRequest>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::set_reset_para >::value();
  }
  static const char* value(const ::inspire_hand::set_reset_paraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::inspire_hand::set_reset_paraResponse> should match 
// service_traits::MD5Sum< ::inspire_hand::set_reset_para > 
template<>
struct MD5Sum< ::inspire_hand::set_reset_paraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::set_reset_para >::value();
  }
  static const char* value(const ::inspire_hand::set_reset_paraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::set_reset_paraResponse> should match 
// service_traits::DataType< ::inspire_hand::set_reset_para > 
template<>
struct DataType< ::inspire_hand::set_reset_paraResponse>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::set_reset_para >::value();
  }
  static const char* value(const ::inspire_hand::set_reset_paraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_SET_RESET_PARA_H
