// Generated by gencpp from file inspire_hand/set_clear_error.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_SET_CLEAR_ERROR_H
#define INSPIRE_HAND_MESSAGE_SET_CLEAR_ERROR_H

#include <ros/service_traits.h>


#include <inspire_hand/set_clear_errorRequest.h>
#include <inspire_hand/set_clear_errorResponse.h>


namespace inspire_hand
{

struct set_clear_error
{

typedef set_clear_errorRequest Request;
typedef set_clear_errorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_clear_error
} // namespace inspire_hand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::inspire_hand::set_clear_error > {
  static const char* value()
  {
    return "a7e6099bc802656c2632bf2a50f44b2b";
  }

  static const char* value(const ::inspire_hand::set_clear_error&) { return value(); }
};

template<>
struct DataType< ::inspire_hand::set_clear_error > {
  static const char* value()
  {
    return "inspire_hand/set_clear_error";
  }

  static const char* value(const ::inspire_hand::set_clear_error&) { return value(); }
};


// service_traits::MD5Sum< ::inspire_hand::set_clear_errorRequest> should match 
// service_traits::MD5Sum< ::inspire_hand::set_clear_error > 
template<>
struct MD5Sum< ::inspire_hand::set_clear_errorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::set_clear_error >::value();
  }
  static const char* value(const ::inspire_hand::set_clear_errorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::set_clear_errorRequest> should match 
// service_traits::DataType< ::inspire_hand::set_clear_error > 
template<>
struct DataType< ::inspire_hand::set_clear_errorRequest>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::set_clear_error >::value();
  }
  static const char* value(const ::inspire_hand::set_clear_errorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::inspire_hand::set_clear_errorResponse> should match 
// service_traits::MD5Sum< ::inspire_hand::set_clear_error > 
template<>
struct MD5Sum< ::inspire_hand::set_clear_errorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::set_clear_error >::value();
  }
  static const char* value(const ::inspire_hand::set_clear_errorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::set_clear_errorResponse> should match 
// service_traits::DataType< ::inspire_hand::set_clear_error > 
template<>
struct DataType< ::inspire_hand::set_clear_errorResponse>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::set_clear_error >::value();
  }
  static const char* value(const ::inspire_hand::set_clear_errorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_SET_CLEAR_ERROR_H
