// Generated by gencpp from file inspire_hand/set_force.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_SET_FORCE_H
#define INSPIRE_HAND_MESSAGE_SET_FORCE_H

#include <ros/service_traits.h>


#include <inspire_hand/set_forceRequest.h>
#include <inspire_hand/set_forceResponse.h>


namespace inspire_hand
{

struct set_force
{

typedef set_forceRequest Request;
typedef set_forceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_force
} // namespace inspire_hand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::inspire_hand::set_force > {
  static const char* value()
  {
    return "f0c08814d46342da9135d3a2a4ea2666";
  }

  static const char* value(const ::inspire_hand::set_force&) { return value(); }
};

template<>
struct DataType< ::inspire_hand::set_force > {
  static const char* value()
  {
    return "inspire_hand/set_force";
  }

  static const char* value(const ::inspire_hand::set_force&) { return value(); }
};


// service_traits::MD5Sum< ::inspire_hand::set_forceRequest> should match 
// service_traits::MD5Sum< ::inspire_hand::set_force > 
template<>
struct MD5Sum< ::inspire_hand::set_forceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::set_force >::value();
  }
  static const char* value(const ::inspire_hand::set_forceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::set_forceRequest> should match 
// service_traits::DataType< ::inspire_hand::set_force > 
template<>
struct DataType< ::inspire_hand::set_forceRequest>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::set_force >::value();
  }
  static const char* value(const ::inspire_hand::set_forceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::inspire_hand::set_forceResponse> should match 
// service_traits::MD5Sum< ::inspire_hand::set_force > 
template<>
struct MD5Sum< ::inspire_hand::set_forceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::set_force >::value();
  }
  static const char* value(const ::inspire_hand::set_forceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::set_forceResponse> should match 
// service_traits::DataType< ::inspire_hand::set_force > 
template<>
struct DataType< ::inspire_hand::set_forceResponse>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::set_force >::value();
  }
  static const char* value(const ::inspire_hand::set_forceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_SET_FORCE_H
