// Generated by gencpp from file inspire_hand/set_gesture_noResponse.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_SET_GESTURE_NORESPONSE_H
#define INSPIRE_HAND_MESSAGE_SET_GESTURE_NORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inspire_hand
{
template <class ContainerAllocator>
struct set_gesture_noResponse_
{
  typedef set_gesture_noResponse_<ContainerAllocator> Type;

  set_gesture_noResponse_()
    : gesture_nograb(false)  {
    }
  set_gesture_noResponse_(const ContainerAllocator& _alloc)
    : gesture_nograb(false)  {
  (void)_alloc;
    }



   typedef uint8_t _gesture_nograb_type;
  _gesture_nograb_type gesture_nograb;





  typedef boost::shared_ptr< ::inspire_hand::set_gesture_noResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inspire_hand::set_gesture_noResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_gesture_noResponse_

typedef ::inspire_hand::set_gesture_noResponse_<std::allocator<void> > set_gesture_noResponse;

typedef boost::shared_ptr< ::inspire_hand::set_gesture_noResponse > set_gesture_noResponsePtr;
typedef boost::shared_ptr< ::inspire_hand::set_gesture_noResponse const> set_gesture_noResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inspire_hand::set_gesture_noResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inspire_hand::set_gesture_noResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inspire_hand

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::set_gesture_noResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::set_gesture_noResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::set_gesture_noResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::set_gesture_noResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::set_gesture_noResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::set_gesture_noResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inspire_hand::set_gesture_noResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "824a75c5329ea6ddcb5d80fa3550cb1c";
  }

  static const char* value(const ::inspire_hand::set_gesture_noResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x824a75c5329ea6ddULL;
  static const uint64_t static_value2 = 0xcb5d80fa3550cb1cULL;
};

template<class ContainerAllocator>
struct DataType< ::inspire_hand::set_gesture_noResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inspire_hand/set_gesture_noResponse";
  }

  static const char* value(const ::inspire_hand::set_gesture_noResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inspire_hand::set_gesture_noResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool gesture_nograb\n\
\n\
";
  }

  static const char* value(const ::inspire_hand::set_gesture_noResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inspire_hand::set_gesture_noResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gesture_nograb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_gesture_noResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inspire_hand::set_gesture_noResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inspire_hand::set_gesture_noResponse_<ContainerAllocator>& v)
  {
    s << indent << "gesture_nograb: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gesture_nograb);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_SET_GESTURE_NORESPONSE_H
