// Generated by gencpp from file inspire_hand/set_force_clb.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_SET_FORCE_CLB_H
#define INSPIRE_HAND_MESSAGE_SET_FORCE_CLB_H

#include <ros/service_traits.h>


#include <inspire_hand/set_force_clbRequest.h>
#include <inspire_hand/set_force_clbResponse.h>


namespace inspire_hand
{

struct set_force_clb
{

typedef set_force_clbRequest Request;
typedef set_force_clbResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_force_clb
} // namespace inspire_hand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::inspire_hand::set_force_clb > {
  static const char* value()
  {
    return "1ed618c9431c8faa2d80a957bf7da809";
  }

  static const char* value(const ::inspire_hand::set_force_clb&) { return value(); }
};

template<>
struct DataType< ::inspire_hand::set_force_clb > {
  static const char* value()
  {
    return "inspire_hand/set_force_clb";
  }

  static const char* value(const ::inspire_hand::set_force_clb&) { return value(); }
};


// service_traits::MD5Sum< ::inspire_hand::set_force_clbRequest> should match 
// service_traits::MD5Sum< ::inspire_hand::set_force_clb > 
template<>
struct MD5Sum< ::inspire_hand::set_force_clbRequest>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::set_force_clb >::value();
  }
  static const char* value(const ::inspire_hand::set_force_clbRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::set_force_clbRequest> should match 
// service_traits::DataType< ::inspire_hand::set_force_clb > 
template<>
struct DataType< ::inspire_hand::set_force_clbRequest>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::set_force_clb >::value();
  }
  static const char* value(const ::inspire_hand::set_force_clbRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::inspire_hand::set_force_clbResponse> should match 
// service_traits::MD5Sum< ::inspire_hand::set_force_clb > 
template<>
struct MD5Sum< ::inspire_hand::set_force_clbResponse>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::set_force_clb >::value();
  }
  static const char* value(const ::inspire_hand::set_force_clbResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::set_force_clbResponse> should match 
// service_traits::DataType< ::inspire_hand::set_force_clb > 
template<>
struct DataType< ::inspire_hand::set_force_clbResponse>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::set_force_clb >::value();
  }
  static const char* value(const ::inspire_hand::set_force_clbResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_SET_FORCE_CLB_H
