// Generated by gencpp from file inspire_hand/set_default_force.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_SET_DEFAULT_FORCE_H
#define INSPIRE_HAND_MESSAGE_SET_DEFAULT_FORCE_H

#include <ros/service_traits.h>


#include <inspire_hand/set_default_forceRequest.h>
#include <inspire_hand/set_default_forceResponse.h>


namespace inspire_hand
{

struct set_default_force
{

typedef set_default_forceRequest Request;
typedef set_default_forceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_default_force
} // namespace inspire_hand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::inspire_hand::set_default_force > {
  static const char* value()
  {
    return "ee9e1744a60012332db6529559adffe2";
  }

  static const char* value(const ::inspire_hand::set_default_force&) { return value(); }
};

template<>
struct DataType< ::inspire_hand::set_default_force > {
  static const char* value()
  {
    return "inspire_hand/set_default_force";
  }

  static const char* value(const ::inspire_hand::set_default_force&) { return value(); }
};


// service_traits::MD5Sum< ::inspire_hand::set_default_forceRequest> should match 
// service_traits::MD5Sum< ::inspire_hand::set_default_force > 
template<>
struct MD5Sum< ::inspire_hand::set_default_forceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::set_default_force >::value();
  }
  static const char* value(const ::inspire_hand::set_default_forceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::set_default_forceRequest> should match 
// service_traits::DataType< ::inspire_hand::set_default_force > 
template<>
struct DataType< ::inspire_hand::set_default_forceRequest>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::set_default_force >::value();
  }
  static const char* value(const ::inspire_hand::set_default_forceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::inspire_hand::set_default_forceResponse> should match 
// service_traits::MD5Sum< ::inspire_hand::set_default_force > 
template<>
struct MD5Sum< ::inspire_hand::set_default_forceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::set_default_force >::value();
  }
  static const char* value(const ::inspire_hand::set_default_forceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::set_default_forceResponse> should match 
// service_traits::DataType< ::inspire_hand::set_default_force > 
template<>
struct DataType< ::inspire_hand::set_default_forceResponse>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::set_default_force >::value();
  }
  static const char* value(const ::inspire_hand::set_default_forceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_SET_DEFAULT_FORCE_H
