// Generated by gencpp from file inspire_hand/set_default_speedRequest.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_SET_DEFAULT_SPEEDREQUEST_H
#define INSPIRE_HAND_MESSAGE_SET_DEFAULT_SPEEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inspire_hand
{
template <class ContainerAllocator>
struct set_default_speedRequest_
{
  typedef set_default_speedRequest_<ContainerAllocator> Type;

  set_default_speedRequest_()
    : speed0(0)
    , speed1(0)
    , speed2(0)
    , speed3(0)
    , speed4(0)
    , speed5(0)  {
    }
  set_default_speedRequest_(const ContainerAllocator& _alloc)
    : speed0(0)
    , speed1(0)
    , speed2(0)
    , speed3(0)
    , speed4(0)
    , speed5(0)  {
  (void)_alloc;
    }



   typedef int32_t _speed0_type;
  _speed0_type speed0;

   typedef int32_t _speed1_type;
  _speed1_type speed1;

   typedef int32_t _speed2_type;
  _speed2_type speed2;

   typedef int32_t _speed3_type;
  _speed3_type speed3;

   typedef int32_t _speed4_type;
  _speed4_type speed4;

   typedef int32_t _speed5_type;
  _speed5_type speed5;





  typedef boost::shared_ptr< ::inspire_hand::set_default_speedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inspire_hand::set_default_speedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_default_speedRequest_

typedef ::inspire_hand::set_default_speedRequest_<std::allocator<void> > set_default_speedRequest;

typedef boost::shared_ptr< ::inspire_hand::set_default_speedRequest > set_default_speedRequestPtr;
typedef boost::shared_ptr< ::inspire_hand::set_default_speedRequest const> set_default_speedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inspire_hand::set_default_speedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inspire_hand::set_default_speedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inspire_hand

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::set_default_speedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::set_default_speedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::set_default_speedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::set_default_speedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::set_default_speedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::set_default_speedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inspire_hand::set_default_speedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b81c1887290eb799831f63509865cac";
  }

  static const char* value(const ::inspire_hand::set_default_speedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b81c1887290eb79ULL;
  static const uint64_t static_value2 = 0x9831f63509865cacULL;
};

template<class ContainerAllocator>
struct DataType< ::inspire_hand::set_default_speedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inspire_hand/set_default_speedRequest";
  }

  static const char* value(const ::inspire_hand::set_default_speedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inspire_hand::set_default_speedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 speed0\n\
int32 speed1\n\
int32 speed2\n\
int32 speed3\n\
int32 speed4\n\
int32 speed5\n\
";
  }

  static const char* value(const ::inspire_hand::set_default_speedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inspire_hand::set_default_speedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed0);
      stream.next(m.speed1);
      stream.next(m.speed2);
      stream.next(m.speed3);
      stream.next(m.speed4);
      stream.next(m.speed5);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_default_speedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inspire_hand::set_default_speedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inspire_hand::set_default_speedRequest_<ContainerAllocator>& v)
  {
    s << indent << "speed0: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed0);
    s << indent << "speed1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed1);
    s << indent << "speed2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed2);
    s << indent << "speed3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed3);
    s << indent << "speed4: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed4);
    s << indent << "speed5: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed5);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_SET_DEFAULT_SPEEDREQUEST_H
