// Generated by gencpp from file inspire_hand/set_force_clbResponse.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_SET_FORCE_CLBRESPONSE_H
#define INSPIRE_HAND_MESSAGE_SET_FORCE_CLBRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inspire_hand
{
template <class ContainerAllocator>
struct set_force_clbResponse_
{
  typedef set_force_clbResponse_<ContainerAllocator> Type;

  set_force_clbResponse_()
    : setforce_clb_accepted(false)  {
    }
  set_force_clbResponse_(const ContainerAllocator& _alloc)
    : setforce_clb_accepted(false)  {
  (void)_alloc;
    }



   typedef uint8_t _setforce_clb_accepted_type;
  _setforce_clb_accepted_type setforce_clb_accepted;





  typedef boost::shared_ptr< ::inspire_hand::set_force_clbResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inspire_hand::set_force_clbResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_force_clbResponse_

typedef ::inspire_hand::set_force_clbResponse_<std::allocator<void> > set_force_clbResponse;

typedef boost::shared_ptr< ::inspire_hand::set_force_clbResponse > set_force_clbResponsePtr;
typedef boost::shared_ptr< ::inspire_hand::set_force_clbResponse const> set_force_clbResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inspire_hand::set_force_clbResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inspire_hand::set_force_clbResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inspire_hand

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::set_force_clbResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::set_force_clbResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::set_force_clbResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::set_force_clbResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::set_force_clbResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::set_force_clbResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inspire_hand::set_force_clbResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ed618c9431c8faa2d80a957bf7da809";
  }

  static const char* value(const ::inspire_hand::set_force_clbResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ed618c9431c8faaULL;
  static const uint64_t static_value2 = 0x2d80a957bf7da809ULL;
};

template<class ContainerAllocator>
struct DataType< ::inspire_hand::set_force_clbResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inspire_hand/set_force_clbResponse";
  }

  static const char* value(const ::inspire_hand::set_force_clbResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inspire_hand::set_force_clbResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool setforce_clb_accepted\n\
\n\
";
  }

  static const char* value(const ::inspire_hand::set_force_clbResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inspire_hand::set_force_clbResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.setforce_clb_accepted);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_force_clbResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inspire_hand::set_force_clbResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inspire_hand::set_force_clbResponse_<ContainerAllocator>& v)
  {
    s << indent << "setforce_clb_accepted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.setforce_clb_accepted);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_SET_FORCE_CLBRESPONSE_H
