// Generated by gencpp from file inspire_hand/set_id.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_SET_ID_H
#define INSPIRE_HAND_MESSAGE_SET_ID_H

#include <ros/service_traits.h>


#include <inspire_hand/set_idRequest.h>
#include <inspire_hand/set_idResponse.h>


namespace inspire_hand
{

struct set_id
{

typedef set_idRequest Request;
typedef set_idResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_id
} // namespace inspire_hand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::inspire_hand::set_id > {
  static const char* value()
  {
    return "5d26ecd99832c8b42f5065ef1190a622";
  }

  static const char* value(const ::inspire_hand::set_id&) { return value(); }
};

template<>
struct DataType< ::inspire_hand::set_id > {
  static const char* value()
  {
    return "inspire_hand/set_id";
  }

  static const char* value(const ::inspire_hand::set_id&) { return value(); }
};


// service_traits::MD5Sum< ::inspire_hand::set_idRequest> should match 
// service_traits::MD5Sum< ::inspire_hand::set_id > 
template<>
struct MD5Sum< ::inspire_hand::set_idRequest>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::set_id >::value();
  }
  static const char* value(const ::inspire_hand::set_idRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::set_idRequest> should match 
// service_traits::DataType< ::inspire_hand::set_id > 
template<>
struct DataType< ::inspire_hand::set_idRequest>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::set_id >::value();
  }
  static const char* value(const ::inspire_hand::set_idRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::inspire_hand::set_idResponse> should match 
// service_traits::MD5Sum< ::inspire_hand::set_id > 
template<>
struct MD5Sum< ::inspire_hand::set_idResponse>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::set_id >::value();
  }
  static const char* value(const ::inspire_hand::set_idResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::set_idResponse> should match 
// service_traits::DataType< ::inspire_hand::set_id > 
template<>
struct DataType< ::inspire_hand::set_idResponse>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::set_id >::value();
  }
  static const char* value(const ::inspire_hand::set_idResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_SET_ID_H
