// Generated by gencpp from file inspire_hand/set_speed.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_SET_SPEED_H
#define INSPIRE_HAND_MESSAGE_SET_SPEED_H

#include <ros/service_traits.h>


#include <inspire_hand/set_speedRequest.h>
#include <inspire_hand/set_speedResponse.h>


namespace inspire_hand
{

struct set_speed
{

typedef set_speedRequest Request;
typedef set_speedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_speed
} // namespace inspire_hand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::inspire_hand::set_speed > {
  static const char* value()
  {
    return "9679dcfdc38eebef480b0c5f0f9a084d";
  }

  static const char* value(const ::inspire_hand::set_speed&) { return value(); }
};

template<>
struct DataType< ::inspire_hand::set_speed > {
  static const char* value()
  {
    return "inspire_hand/set_speed";
  }

  static const char* value(const ::inspire_hand::set_speed&) { return value(); }
};


// service_traits::MD5Sum< ::inspire_hand::set_speedRequest> should match 
// service_traits::MD5Sum< ::inspire_hand::set_speed > 
template<>
struct MD5Sum< ::inspire_hand::set_speedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::set_speed >::value();
  }
  static const char* value(const ::inspire_hand::set_speedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::set_speedRequest> should match 
// service_traits::DataType< ::inspire_hand::set_speed > 
template<>
struct DataType< ::inspire_hand::set_speedRequest>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::set_speed >::value();
  }
  static const char* value(const ::inspire_hand::set_speedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::inspire_hand::set_speedResponse> should match 
// service_traits::MD5Sum< ::inspire_hand::set_speed > 
template<>
struct MD5Sum< ::inspire_hand::set_speedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::inspire_hand::set_speed >::value();
  }
  static const char* value(const ::inspire_hand::set_speedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::inspire_hand::set_speedResponse> should match 
// service_traits::DataType< ::inspire_hand::set_speed > 
template<>
struct DataType< ::inspire_hand::set_speedResponse>
{
  static const char* value()
  {
    return DataType< ::inspire_hand::set_speed >::value();
  }
  static const char* value(const ::inspire_hand::set_speedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_SET_SPEED_H
