// Generated by gencpp from file inspire_hand/set_forceResponse.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_SET_FORCERESPONSE_H
#define INSPIRE_HAND_MESSAGE_SET_FORCERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inspire_hand
{
template <class ContainerAllocator>
struct set_forceResponse_
{
  typedef set_forceResponse_<ContainerAllocator> Type;

  set_forceResponse_()
    : force_accepted(false)  {
    }
  set_forceResponse_(const ContainerAllocator& _alloc)
    : force_accepted(false)  {
  (void)_alloc;
    }



   typedef uint8_t _force_accepted_type;
  _force_accepted_type force_accepted;





  typedef boost::shared_ptr< ::inspire_hand::set_forceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inspire_hand::set_forceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_forceResponse_

typedef ::inspire_hand::set_forceResponse_<std::allocator<void> > set_forceResponse;

typedef boost::shared_ptr< ::inspire_hand::set_forceResponse > set_forceResponsePtr;
typedef boost::shared_ptr< ::inspire_hand::set_forceResponse const> set_forceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inspire_hand::set_forceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inspire_hand::set_forceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inspire_hand

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::set_forceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::set_forceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::set_forceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::set_forceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::set_forceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::set_forceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inspire_hand::set_forceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6133e5998441599a96899c74dc63d85d";
  }

  static const char* value(const ::inspire_hand::set_forceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6133e5998441599aULL;
  static const uint64_t static_value2 = 0x96899c74dc63d85dULL;
};

template<class ContainerAllocator>
struct DataType< ::inspire_hand::set_forceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inspire_hand/set_forceResponse";
  }

  static const char* value(const ::inspire_hand::set_forceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inspire_hand::set_forceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool force_accepted\n\
\n\
";
  }

  static const char* value(const ::inspire_hand::set_forceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inspire_hand::set_forceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.force_accepted);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_forceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inspire_hand::set_forceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inspire_hand::set_forceResponse_<ContainerAllocator>& v)
  {
    s << indent << "force_accepted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.force_accepted);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_SET_FORCERESPONSE_H
