// Generated by gencpp from file inspire_hand/set_gesture_noRequest.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_SET_GESTURE_NOREQUEST_H
#define INSPIRE_HAND_MESSAGE_SET_GESTURE_NOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inspire_hand
{
template <class ContainerAllocator>
struct set_gesture_noRequest_
{
  typedef set_gesture_noRequest_<ContainerAllocator> Type;

  set_gesture_noRequest_()
    : gesture_no(0)  {
    }
  set_gesture_noRequest_(const ContainerAllocator& _alloc)
    : gesture_no(0)  {
  (void)_alloc;
    }



   typedef int32_t _gesture_no_type;
  _gesture_no_type gesture_no;





  typedef boost::shared_ptr< ::inspire_hand::set_gesture_noRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inspire_hand::set_gesture_noRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_gesture_noRequest_

typedef ::inspire_hand::set_gesture_noRequest_<std::allocator<void> > set_gesture_noRequest;

typedef boost::shared_ptr< ::inspire_hand::set_gesture_noRequest > set_gesture_noRequestPtr;
typedef boost::shared_ptr< ::inspire_hand::set_gesture_noRequest const> set_gesture_noRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inspire_hand::set_gesture_noRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inspire_hand::set_gesture_noRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inspire_hand

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::set_gesture_noRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::set_gesture_noRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::set_gesture_noRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::set_gesture_noRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::set_gesture_noRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::set_gesture_noRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inspire_hand::set_gesture_noRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea289c543a56bf8388893db17ebece7f";
  }

  static const char* value(const ::inspire_hand::set_gesture_noRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea289c543a56bf83ULL;
  static const uint64_t static_value2 = 0x88893db17ebece7fULL;
};

template<class ContainerAllocator>
struct DataType< ::inspire_hand::set_gesture_noRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inspire_hand/set_gesture_noRequest";
  }

  static const char* value(const ::inspire_hand::set_gesture_noRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inspire_hand::set_gesture_noRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 gesture_no\n\
";
  }

  static const char* value(const ::inspire_hand::set_gesture_noRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inspire_hand::set_gesture_noRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gesture_no);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_gesture_noRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inspire_hand::set_gesture_noRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inspire_hand::set_gesture_noRequest_<ContainerAllocator>& v)
  {
    s << indent << "gesture_no: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gesture_no);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_SET_GESTURE_NOREQUEST_H
