// Generated by gencpp from file inspire_hand/set_clear_errorResponse.msg
// DO NOT EDIT!


#ifndef INSPIRE_HAND_MESSAGE_SET_CLEAR_ERRORRESPONSE_H
#define INSPIRE_HAND_MESSAGE_SET_CLEAR_ERRORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inspire_hand
{
template <class ContainerAllocator>
struct set_clear_errorResponse_
{
  typedef set_clear_errorResponse_<ContainerAllocator> Type;

  set_clear_errorResponse_()
    : setclear_error_accepted(false)  {
    }
  set_clear_errorResponse_(const ContainerAllocator& _alloc)
    : setclear_error_accepted(false)  {
  (void)_alloc;
    }



   typedef uint8_t _setclear_error_accepted_type;
  _setclear_error_accepted_type setclear_error_accepted;





  typedef boost::shared_ptr< ::inspire_hand::set_clear_errorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inspire_hand::set_clear_errorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_clear_errorResponse_

typedef ::inspire_hand::set_clear_errorResponse_<std::allocator<void> > set_clear_errorResponse;

typedef boost::shared_ptr< ::inspire_hand::set_clear_errorResponse > set_clear_errorResponsePtr;
typedef boost::shared_ptr< ::inspire_hand::set_clear_errorResponse const> set_clear_errorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inspire_hand::set_clear_errorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inspire_hand::set_clear_errorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inspire_hand

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::set_clear_errorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inspire_hand::set_clear_errorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::set_clear_errorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inspire_hand::set_clear_errorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::set_clear_errorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inspire_hand::set_clear_errorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inspire_hand::set_clear_errorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7e6099bc802656c2632bf2a50f44b2b";
  }

  static const char* value(const ::inspire_hand::set_clear_errorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7e6099bc802656cULL;
  static const uint64_t static_value2 = 0x2632bf2a50f44b2bULL;
};

template<class ContainerAllocator>
struct DataType< ::inspire_hand::set_clear_errorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inspire_hand/set_clear_errorResponse";
  }

  static const char* value(const ::inspire_hand::set_clear_errorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inspire_hand::set_clear_errorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool setclear_error_accepted\n\
";
  }

  static const char* value(const ::inspire_hand::set_clear_errorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inspire_hand::set_clear_errorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.setclear_error_accepted);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_clear_errorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inspire_hand::set_clear_errorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inspire_hand::set_clear_errorResponse_<ContainerAllocator>& v)
  {
    s << indent << "setclear_error_accepted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.setclear_error_accepted);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INSPIRE_HAND_MESSAGE_SET_CLEAR_ERRORRESPONSE_H
