// Generated by gencpp from file yumi_robot_service/yumi_execute.msg
// DO NOT EDIT!


#ifndef YUMI_ROBOT_SERVICE_MESSAGE_YUMI_EXECUTE_H
#define YUMI_ROBOT_SERVICE_MESSAGE_YUMI_EXECUTE_H

#include <ros/service_traits.h>


#include <yumi_robot_service/yumi_executeRequest.h>
#include <yumi_robot_service/yumi_executeResponse.h>


namespace yumi_robot_service
{

struct yumi_execute
{

typedef yumi_executeRequest Request;
typedef yumi_executeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct yumi_execute
} // namespace yumi_robot_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yumi_robot_service::yumi_execute > {
  static const char* value()
  {
    return "24a5a4d139f797e276899139cf7239b0";
  }

  static const char* value(const ::yumi_robot_service::yumi_execute&) { return value(); }
};

template<>
struct DataType< ::yumi_robot_service::yumi_execute > {
  static const char* value()
  {
    return "yumi_robot_service/yumi_execute";
  }

  static const char* value(const ::yumi_robot_service::yumi_execute&) { return value(); }
};


// service_traits::MD5Sum< ::yumi_robot_service::yumi_executeRequest> should match 
// service_traits::MD5Sum< ::yumi_robot_service::yumi_execute > 
template<>
struct MD5Sum< ::yumi_robot_service::yumi_executeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yumi_robot_service::yumi_execute >::value();
  }
  static const char* value(const ::yumi_robot_service::yumi_executeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yumi_robot_service::yumi_executeRequest> should match 
// service_traits::DataType< ::yumi_robot_service::yumi_execute > 
template<>
struct DataType< ::yumi_robot_service::yumi_executeRequest>
{
  static const char* value()
  {
    return DataType< ::yumi_robot_service::yumi_execute >::value();
  }
  static const char* value(const ::yumi_robot_service::yumi_executeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yumi_robot_service::yumi_executeResponse> should match 
// service_traits::MD5Sum< ::yumi_robot_service::yumi_execute > 
template<>
struct MD5Sum< ::yumi_robot_service::yumi_executeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yumi_robot_service::yumi_execute >::value();
  }
  static const char* value(const ::yumi_robot_service::yumi_executeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yumi_robot_service::yumi_executeResponse> should match 
// service_traits::DataType< ::yumi_robot_service::yumi_execute > 
template<>
struct DataType< ::yumi_robot_service::yumi_executeResponse>
{
  static const char* value()
  {
    return DataType< ::yumi_robot_service::yumi_execute >::value();
  }
  static const char* value(const ::yumi_robot_service::yumi_executeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YUMI_ROBOT_SERVICE_MESSAGE_YUMI_EXECUTE_H
