// Generated by gencpp from file yumi_collision_checking/yumi_execute.msg
// DO NOT EDIT!


#ifndef YUMI_COLLISION_CHECKING_MESSAGE_YUMI_EXECUTE_H
#define YUMI_COLLISION_CHECKING_MESSAGE_YUMI_EXECUTE_H

#include <ros/service_traits.h>


#include <yumi_collision_checking/yumi_executeRequest.h>
#include <yumi_collision_checking/yumi_executeResponse.h>


namespace yumi_collision_checking
{

struct yumi_execute
{

typedef yumi_executeRequest Request;
typedef yumi_executeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct yumi_execute
} // namespace yumi_collision_checking


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yumi_collision_checking::yumi_execute > {
  static const char* value()
  {
    return "b1adf680c6857c95eac390b17b06c828";
  }

  static const char* value(const ::yumi_collision_checking::yumi_execute&) { return value(); }
};

template<>
struct DataType< ::yumi_collision_checking::yumi_execute > {
  static const char* value()
  {
    return "yumi_collision_checking/yumi_execute";
  }

  static const char* value(const ::yumi_collision_checking::yumi_execute&) { return value(); }
};


// service_traits::MD5Sum< ::yumi_collision_checking::yumi_executeRequest> should match 
// service_traits::MD5Sum< ::yumi_collision_checking::yumi_execute > 
template<>
struct MD5Sum< ::yumi_collision_checking::yumi_executeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yumi_collision_checking::yumi_execute >::value();
  }
  static const char* value(const ::yumi_collision_checking::yumi_executeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yumi_collision_checking::yumi_executeRequest> should match 
// service_traits::DataType< ::yumi_collision_checking::yumi_execute > 
template<>
struct DataType< ::yumi_collision_checking::yumi_executeRequest>
{
  static const char* value()
  {
    return DataType< ::yumi_collision_checking::yumi_execute >::value();
  }
  static const char* value(const ::yumi_collision_checking::yumi_executeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yumi_collision_checking::yumi_executeResponse> should match 
// service_traits::MD5Sum< ::yumi_collision_checking::yumi_execute > 
template<>
struct MD5Sum< ::yumi_collision_checking::yumi_executeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yumi_collision_checking::yumi_execute >::value();
  }
  static const char* value(const ::yumi_collision_checking::yumi_executeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yumi_collision_checking::yumi_executeResponse> should match 
// service_traits::DataType< ::yumi_collision_checking::yumi_execute > 
template<>
struct DataType< ::yumi_collision_checking::yumi_executeResponse>
{
  static const char* value()
  {
    return DataType< ::yumi_collision_checking::yumi_execute >::value();
  }
  static const char* value(const ::yumi_collision_checking::yumi_executeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YUMI_COLLISION_CHECKING_MESSAGE_YUMI_EXECUTE_H
