# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from inspire_hand/set_current_limitRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class set_current_limitRequest(genpy.Message):
  _md5sum = "9a9062b22d95e0929b8d48bafef48d49"
  _type = "inspire_hand/set_current_limitRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 current0
int32 current1
int32 current2
int32 current3
int32 current4
int32 current5
"""
  __slots__ = ['current0','current1','current2','current3','current4','current5']
  _slot_types = ['int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       current0,current1,current2,current3,current4,current5

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(set_current_limitRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.current0 is None:
        self.current0 = 0
      if self.current1 is None:
        self.current1 = 0
      if self.current2 is None:
        self.current2 = 0
      if self.current3 is None:
        self.current3 = 0
      if self.current4 is None:
        self.current4 = 0
      if self.current5 is None:
        self.current5 = 0
    else:
      self.current0 = 0
      self.current1 = 0
      self.current2 = 0
      self.current3 = 0
      self.current4 = 0
      self.current5 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6i().pack(_x.current0, _x.current1, _x.current2, _x.current3, _x.current4, _x.current5))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.current0, _x.current1, _x.current2, _x.current3, _x.current4, _x.current5,) = _get_struct_6i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6i().pack(_x.current0, _x.current1, _x.current2, _x.current3, _x.current4, _x.current5))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.current0, _x.current1, _x.current2, _x.current3, _x.current4, _x.current5,) = _get_struct_6i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6i = None
def _get_struct_6i():
    global _struct_6i
    if _struct_6i is None:
        _struct_6i = struct.Struct("<6i")
    return _struct_6i
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from inspire_hand/set_current_limitResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class set_current_limitResponse(genpy.Message):
  _md5sum = "91307348c21336c78336107026a1dcce"
  _type = "inspire_hand/set_current_limitResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool current_limit_accepted
"""
  __slots__ = ['current_limit_accepted']
  _slot_types = ['bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       current_limit_accepted

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(set_current_limitResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.current_limit_accepted is None:
        self.current_limit_accepted = False
    else:
      self.current_limit_accepted = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_B().pack(self.current_limit_accepted))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 1
      (self.current_limit_accepted,) = _get_struct_B().unpack(str[start:end])
      self.current_limit_accepted = bool(self.current_limit_accepted)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_B().pack(self.current_limit_accepted))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 1
      (self.current_limit_accepted,) = _get_struct_B().unpack(str[start:end])
      self.current_limit_accepted = bool(self.current_limit_accepted)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class set_current_limit(object):
  _type          = 'inspire_hand/set_current_limit'
  _md5sum = '422c9f6eddce4f2b83bdd05a0c49ffe4'
  _request_class  = set_current_limitRequest
  _response_class = set_current_limitResponse
